Metrics/LineLength:
  Max: 120

Style/SingleLineBlockParams:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StabbyLambdaParentheses:
  Enabled: false

AllCops:
  DisplayCopNames: true
