require_relative 'domain/die'
require_relative 'domain/dice'
require_relative 'domain/iteration'
require_relative 'domain/random_roller'
require_relative 'domain/persistence'
require_relative 'domain/game'
