require_relative 'persistence/configuration'
require_relative 'persistence/auto_register'
require_relative 'persistence/rom'
require_relative 'persistence/repository'
require_relative 'persistence/iterations'
require_relative 'persistence/rolls'
require_relative 'persistence/games'
